apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: stefanias98/myserver
          ports:
            - containerPort: 2000
          env:
            - name: PORT_SERVER
              value: "2000"